require 'bundler'
Bundler::GemHelper.install_tasks

require "rspec"
require "rspec/core/rake_task"

$LOAD_PATH.unshift File.expand_path("../lib", __FILE__)
require "bstree/version"

task :build do
  system "gem build bstree.gemspec"
end

task :install => :build do
  system "sudo gem install bstree-#{BSTree::VERSION}.gem"
end

task :release => :build do
  puts "Tagging #{BSTree::VERSION}..."
  system "git tag -a #{BSTree::VERSION} -m 'Tagging #{BSTree::VERSION}'"
  puts "Pushing to Github..."
  system "git push --tags"
  puts "Pushing to rubygems.org..."
  system "gem push bstree-#{BSTree::VERSION}.gem"
end

Rspec::Core::RakeTask.new(:spec) do |spec|
  spec.pattern = "spec/**/*_spec.rb"
end

Rspec::Core::RakeTask.new('spec:progress') do |spec|
  spec.rspec_opts = %w(--format progress)
  spec.pattern = "spec/**/*_spec.rb"
end

task :default => :spec
task :test => :spec
